trigger:
- master
- v1.x
- azure-pipelines

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'run'
    workingDirectory: '.\build'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\artifacts'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
